import { z } from "zod";

export const BlockTypeEnum = z.enum(["header","hero","features","services","testimonials","contact","map","tabs","footer"]);

export const BlockSchema = z.object({
  id: z.string(),
  type: BlockTypeEnum,
  variant: z.string().default("default"),
  props: z.record(z.string(), z.any()).default({}),
});

export const SiteSchema = z.object({
  _id: z.string().optional(),
  siteId: z.string(),
  ownerId: z.string().optional(),
  title: z.string().default("Untitled"),
  seo: z.object({ title: z.string(), description: z.string().optional() }).optional(),
  theme: z.object({
    primary: z.string(),
    accent: z.string().optional(),
    fontFamily: z.string().default("Inter"),
  }),
  // Multi-page sites: each page has its own code bundle
  pages: z
    .array(
      z.object({
        path: z.string(),
        title: z.string().optional(),
        code: z.object({ html: z.string(), css: z.string().optional() }),
      })
    )
    .default([]),
  // Optional code-based site rendering (HTML/CSS generated by AI)
  code: z
    .object({
      html: z.string(),
      css: z.string().optional(),
    })
    .optional(),
  // For block-based rendering; default to empty for code-only sites
  blocks: z.array(BlockSchema).default([]),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
});

export type Site = z.infer<typeof SiteSchema>;
export type Block = z.infer<typeof BlockSchema>;


